title: "FedRAMP Automation"
baseURL: https://automate.fedramp.gov/
defaultContentLanguage: en
languageCode: "en-us"
MetaDataFormat: "yaml"
#googleAnalytics: UA-
enableGitInfo: true
enableRobotsTXT: true
menu:
  secondary:
  - name: FedRAMP
    url: https://fedramp.gov/
    weight: 10
  - name: Marketplace
    url: https://marketplace.fedramp.gov/
    weight: 10
  - name: Github
    url: https://github.com/GSA/fedramp-automation
    weight: 90
# Configuration for hugo-uswds
#
module:
  mounts:
  - source: static
    target: static
  - source: static/img
    target: assets/img
  - source: ../examples
    target: static/examples
#  imports:
#  - path: github.com/GSA/uswds-hugo
theme:
- uswds-hugo
params:
  header:
    project_shortname: "Automation"
    project_name: "Automation"
  page_repo_path: https://github.com/GSA/automate.fedramp.gov/blob/develop/content
  contentRepoPath: https://github.com/GSA/automate.fedramp.gov/blob/develop/content
  usabanner: true
  sidenav:
  custom_css:
  - /css/site.css
  searchAffiliate: fedramp-automation
#    debug: true
markup:
  goldmark: # Markdown Rendering
    renderer:
      unsafe: true # required for the Hugo USWDS theme
  highlight: # Code Highlighting
    guessSyntax: true
    noClasses: false # enables USWDS styled syntax highlighting
